apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: codegen-004-gitops
  description: This is GitOps manifest for codegen-004   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: codegen-004
    janus-idp.io/tekton: codegen-004 
    backstage.io/kubernetes-id: codegen-004 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:default/skitamura7446 
  lifecycle: experimental
  dependsOn:
    - component:codegen-004
